//
// Copyright 2019 - 2025 (C). Alex Robenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "CommsGenerator.h"

#include "CommsBitfieldField.h"
#include "CommsBundleField.h"
#include "CommsChecksumLayer.h"
#include "CommsCmake.h"
#include "CommsCustomLayer.h"
#include "CommsDataField.h"
#include "CommsDefaultOptions.h"
#include "CommsDoxygen.h"
#include "CommsEnumField.h"
#include "CommsFieldBase.h"
#include "CommsFloatField.h"
#include "CommsFrame.h"
#include "CommsInputMessages.h"
#include "CommsIntField.h"
#include "CommsListField.h"
#include "CommsIdLayer.h"
#include "CommsInterface.h"
#include "CommsMessage.h"
#include "CommsNamespace.h"
#include "CommsOptionalField.h"
#include "CommsPayloadLayer.h"
#include "CommsProgramOptions.h"
#include "CommsRefField.h"
#include "CommsSchema.h"
#include "CommsSetField.h"
#include "CommsSizeLayer.h"
#include "CommsSyncLayer.h"
#include "CommsStringField.h"
#include "CommsValueLayer.h"
#include "CommsVariantField.h"
#include "CommsVersion.h"

#include "commsdsl/version.h"
#include "commsdsl/gen/strings.h"
#include "commsdsl/gen/util.h"

#include <algorithm>
#include <cassert>
#include <iterator>
#include <filesystem>
#include <fstream>
#include <system_error>
#include <type_traits>

namespace fs = std::filesystem;
namespace strings = commsdsl::gen::strings;
namespace util = commsdsl::gen::util;

namespace commsdsl2comms
{

const std::string CommsMinCommsVersion("5.4.5");

const std::string& CommsGenerator::commsFileGeneratedComment()
{
    static const std::string Str =
        "// Generated by commsdsl2comms v" + std::to_string(commsdsl::versionMajor()) +
        '.' + std::to_string(commsdsl::versionMinor()) + '.' +
        std::to_string(commsdsl::versionPatch()) + '\n';
    return Str;
}

CommsGenerator::CommsCustomizationLevel CommsGenerator::commsGetCustomizationLevel() const
{
    return m_customizationLevel;
}

void CommsGenerator::commsSetCustomizationLevel(const std::string& value)
{
    if (value.empty()) {
        return;
    }

    static const std::string Map[] = {
        /* Full */ "full",
        /* Limited */ "limited",
        /* None */ "none",
    };
    static const std::size_t MapSize = std::extent<decltype(Map)>::value;
    static_assert(MapSize == static_cast<unsigned>(CommsCustomizationLevel::NumOfValues));

    auto iter = std::find(std::begin(Map), std::end(Map), value);
    if (iter == std::end(Map)) {
        genLogger().genWarning("Unknown customization level \"" + value + "\", using default.");
        return;
    }

    m_customizationLevel = static_cast<CommsCustomizationLevel>(std::distance(std::begin(Map), iter));
}

bool CommsGenerator::commsGetMainNamespaceInOptionsForced() const
{
    return m_mainNamespaceInOptionsForced;
}

void CommsGenerator::commsSetMainNamespaceInOptionsForced(bool value)
{
    m_mainNamespaceInOptionsForced = value;
}

bool CommsGenerator::commsHasMainNamespaceInOptions() const
{
    return m_mainNamespaceInOptionsForced || (genSchemas().size() > 1U);
}

const std::vector<std::string>& CommsGenerator::commsGetExtraInputBundles() const
{
    return m_extraInputBundles;
}

void CommsGenerator::commsSetExtraInputBundles(const std::vector<std::string>& inputBundles)
{
    m_extraInputBundles = inputBundles;
}

const CommsGenerator::CommsExtraMessageBundlesList& CommsGenerator::commsExtraMessageBundles() const
{
    return m_commsExtraMessageBundles;
}

const std::string& CommsGenerator::commsMinCommsVersion()
{
    return CommsMinCommsVersion;
}

bool CommsGenerator::genPrepareImpl()
{
    if (!Base::genPrepareImpl()) {
        return false;
    }

    return
        commsPrepareExtraMessageBundlesInternal();
}

CommsGenerator::GenSchemaPtr CommsGenerator::genCreateSchemaImpl(commsdsl::parse::ParseSchema parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsSchema>(*this, parseObj, parent);
}

CommsGenerator::GenNamespacePtr CommsGenerator::genCreateNamespaceImpl(commsdsl::parse::ParseNamespace parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsNamespace>(*this, parseObj, parent);
}

CommsGenerator::GenInterfacePtr CommsGenerator::genCreateInterfaceImpl(commsdsl::parse::ParseInterface parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsInterface>(*this, parseObj, parent);
}

CommsGenerator::GenMessagePtr CommsGenerator::genCreateMessageImpl(commsdsl::parse::ParseMessage parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsMessage>(*this, parseObj, parent);
}

CommsGenerator::GenFramePtr CommsGenerator::genCreateFrameImpl(commsdsl::parse::ParseFrame parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsFrame>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateIntFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsIntField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateEnumFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsEnumField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateSetFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsSetField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateFloatFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsFloatField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateBitfieldFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsBitfieldField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateBundleFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsBundleField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateStringFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsStringField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateDataFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsDataField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateListFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsListField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateRefFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsRefField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateOptionalFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsOptionalField>(*this, parseObj, parent);
}

CommsGenerator::GenFieldPtr CommsGenerator::genCreateVariantFieldImpl(commsdsl::parse::ParseField parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsVariantField>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateCustomLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsCustomLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateSyncLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsSyncLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateSizeLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsSizeLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateIdLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsIdLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateValueLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsValueLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreatePayloadLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsPayloadLayer>(*this, parseObj, parent);
}

CommsGenerator::GenLayerPtr CommsGenerator::genCreateChecksumLayerImpl(commsdsl::parse::ParseLayer parseObj, commsdsl::gen::GenElem* parent)
{
    return std::make_unique<commsdsl2comms::CommsChecksumLayer>(*this, parseObj, parent);
}

bool CommsGenerator::genWriteImpl()
{
    for (auto idx = 0U; idx < genSchemas().size(); ++idx) {
        genChooseCurrentSchema(idx);
        bool result =
            CommsFieldBase::commsWrite(*this) &&
            CommsVersion::commsWrite(*this) &&
            CommsDefaultOptions::commsWrite(*this);

        if (!result) {
            return false;
        }
    }

    assert(&genCurrentSchema() == &genProtocolSchema());
    return
        CommsCmake::commsWrite(*this) &&
        CommsDoxygen::commsWrite(*this) &&
        commsWriteExtraFilesInternal();
}

CommsGenerator::OptsProcessResult CommsGenerator::genProcessOptionsImpl(const GenProgramOptions& options)
{
    auto& opts = CommsProgramOptions::commsCast(options);
    genSetVersionIndependentCodeForced(opts.commsVersionIndependentCodeRequested());
    commsSetCustomizationLevel(opts.commsGetCustomizationLevel());
    commsSetExtraInputBundles(opts.commsGetExtraInputBundles());
    commsSetMainNamespaceInOptionsForced(opts.commsIsMainNamespaceInOptionsForced());

    return OptsProcessResult_Continue;
}

bool CommsGenerator::commsPrepareExtraMessageBundlesInternal()
{
    m_commsExtraMessageBundles.reserve(m_extraInputBundles.size());
    for (auto& b : m_extraInputBundles) {
        std::string name;
        std::string path = b;

        auto sepPos = b.find_first_of('@');
        if (sepPos != std::string::npos) {
            name.assign(b, 0, sepPos);
            path.erase(path.begin(), path.begin() + sepPos + 1);
        }

        if (name.empty()) {
            name = fs::path(path).stem().string();
            genLogger().genDebug("Bundle name from path: " + path + " --> " + name);
        }

        if (name.empty()) {
            genLogger().genError("Failed to idenity bundle name for " + b);
            return false;
        }

        std::ifstream stream(path);
        if (!stream) {
            genLogger().genError("Failed to read extra messages bundle file " + path);
            return false;
        }

        std::string contents(std::istreambuf_iterator<char>(stream), (std::istreambuf_iterator<char>()));
        auto lines = util::genStrSplitByAnyChar(contents, "\n\r");
        GenMessagesAccessList messages;
        messages.reserve(lines.size());

        for (auto& l : lines) {
            auto* m = genGindMessage(l);
            if (m == nullptr) {
                genLogger().genError("Failed to fined message \"" + l + "\" for bundle " + name);
                return false;
            }

            messages.push_back(m);
        }

        genLogger().genDebug("Extra message bundle: " + name);
        m_commsExtraMessageBundles.emplace_back(std::move(name), std::move(messages));
    };
    return true;
}

bool CommsGenerator::commsWriteExtraFilesInternal() const
{
    const std::vector<std::string> ReservedExt = {
        strings::genReplaceFileSuffixStr(),
        strings::genExtendFileSuffixStr(),
        strings::genPublicFileSuffixStr(),
        strings::genProtectedFileSuffixStr(),
        strings::genPrivateFileSuffixStr(),
        strings::genValueFileSuffixStr(),
        strings::genReadFileSuffixStr(),
        strings::genReadBodyFileSuffixStr(),
        strings::genWriteFileSuffixStr(),
        strings::genWriteBodyFileSuffixStr(),
        strings::genLengthFileSuffixStr(),
        strings::genLengthBodyFileSuffixStr(),
        strings::genValidFileSuffixStr(),
        strings::genValidBodyFileSuffixStr(),
        strings::genRefreshFileSuffixStr(),
        strings::genRefreshBodyFileSuffixStr(),
        strings::genNameFileSuffixStr(),
        strings::genNameBodyFileSuffixStr(),
        strings::genIncFileSuffixStr(),
        strings::genAppendFileSuffixStr(),
        strings::genConstructFileSuffixStr(),
    };

    return genCopyExtraSourceFiles(ReservedExt);
}

} // namespace commsdsl2comms
