//
// Copyright 2026 - 2026 (C). Alex Robenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "WiresharkGenerator.h"

#include "Wireshark.h"
#include "WiresharkProgramOptions.h"

#include "commsdsl/gen/strings.h"

#include <cassert>

namespace strings = commsdsl::gen::strings;

namespace commsdsl2wireshark
{

WiresharkGenerator::WiresharkGenerator() = default;

bool WiresharkGenerator::genWriteImpl()
{
    assert(&genCurrentSchema() == &genProtocolSchema());
    return
        Wireshark::wiresharkWrite(*this) &&
        wiresharkWriteExtraFilesInternal();
}

const std::string& WiresharkGenerator::wiresharkFileGeneratedComment()
{
    static const std::string Str =
        "-- Generated by commsdsl2wireshark " + genVersionStr() + '\n';
    return Str;
}

std::string WiresharkGenerator::wiresharkInputRelPathFor(const std::string& name) const
{
    return Wireshark::wiresharkFileName(*this) + '.' + name;
}

std::string WiresharkGenerator::wiresharkInputAbsPathFor(const std::string& name) const
{
    return genGetCodeDir() + '/' + wiresharkInputRelPathFor(name);
}

WiresharkGenerator::OptsProcessResult WiresharkGenerator::genProcessOptionsImpl(
    [[maybe_unused]] const GenProgramOptions& options)
{
    return OptsProcessResult_Continue;
}

const std::string& WiresharkGenerator::genCommentPrefixImpl() const
{
    static const std::string Str("-- ");
    return Str;
}

bool WiresharkGenerator::wiresharkWriteExtraFilesInternal() const
{
    const std::vector<std::string> ReservedExt = {
        strings::genAppendFileSuffixStr(),
        strings::genReplaceFileSuffixStr(),
        strings::genExtendFileSuffixStr(),
    };

    return genCopyExtraSourceFiles(ReservedExt);
}

} // namespace commsdsl2wireshark
