//
// Copyright 2019 - 2025 (C). Alex Robenko. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "TestGenerator.h"

#include "Test.h"
#include "TestCmake.h"

#include "commsdsl/version.h"
#include "commsdsl/gen/strings.h"
#include "commsdsl/gen/util.h"

#include <cassert>
#include <fstream>
#include <filesystem>

namespace fs = std::filesystem;
namespace strings = commsdsl::gen::strings;
namespace util = commsdsl::gen::util;

namespace commsdsl2test
{

const std::string& TestGenerator::testFileGeneratedComment()
{
    static const std::string Str =
        "// Generated by commsdsl2test v" + std::to_string(commsdsl::versionMajor()) +
        '.' + std::to_string(commsdsl::versionMinor()) + '.' +
        std::to_string(commsdsl::versionPatch()) + '\n';
    return Str;
}

bool TestGenerator::genWriteImpl()
{
    assert(&genCurrentSchema() == &genProtocolSchema());
    return 
        Test::testWrite(*this) &&
        TestCmake::testWrite(*this) &&
        testWriteExtraFilesInternal();
}

bool TestGenerator::testWriteExtraFilesInternal() const
{
    const std::vector<std::string> ReservedExt = {
        strings::genSourcesFileSuffixStr(),
    }; 

    return genCopyExtraSourceFiles(ReservedExt);
}

} // namespace commsdsl2test
