macro (commsdsl_negate_option old_name new_name)
    if (DEFINED ${old_name})
        if (${old_name})
            set (${new_name} OFF)
        else ()
            set (${new_name} ON)
        endif ()
    endif ()
endmacro ()

function (commsdsl_platform_specific_link tgt)
    if (WIN32)
        target_link_libraries(${tgt} PRIVATE Setupapi.lib Ws2_32.lib imm32.lib winmm.lib)
    endif ()
endfunction ()