#include "CommsGenerator.h"

#include "CommsCmake.h"
#include "CommsIntField.h"

#include "commsdsl/version.h"

namespace commsdsl2new
{

const std::string& CommsGenerator::fileGeneratedComment()
{
    static const std::string Str =
        "// Generated by commsdsl2new v" + std::to_string(commsdsl::versionMajor()) +
        '.' + std::to_string(commsdsl::versionMinor()) + '.' +
        std::to_string(commsdsl::versionPatch()) + '\n';
    return Str;
}

CommsGenerator::FieldPtr CommsGenerator::createIntFieldImpl(commsdsl::parse::Field dslObj, Elem* parent)
{
    return std::make_unique<commsdsl2new::CommsIntField>(*this, dslObj, parent);
}

bool CommsGenerator::writeImpl()
{
    return 
        CommsCmake::write(*this);
}

} // namespace commsdsl2new
