#include "Generator.h"

#include "commsdsl/version.h"

#include "Cmake.h"

namespace commsdsl2new
{

const std::string& Generator::fileGeneratedComment()
{
    static const std::string Str =
        "// Generated by commsdsl2new v" + std::to_string(commsdsl::versionMajor()) +
        '.' + std::to_string(commsdsl::versionMinor()) + '.' +
        std::to_string(commsdsl::versionPatch()) + '\n';
    return Str;
}

bool Generator::writeImpl()
{
    return 
        Cmake::write(*this);
}

} // namespace commsdsl2new
